// <auto-generated />
using System;
using HerPace.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HerPace.Infrastructure.Migrations
{
    [DbContext(typeof(HerPaceDbContext))]
    [Migration("20260212031538_AddFitnessTrackerEntities")]
    partial class AddFitnessTrackerEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HerPace.Core.Entities.ConnectedService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessToken")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("ConnectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DisconnectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalUserId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastSyncError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Platform")
                        .HasColumnType("integer");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("RunnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Scopes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("TokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RunnerId", "Platform")
                        .IsUnique();

                    b.ToTable("connected_services", (string)null);
                });

            modelBuilder.Entity("HerPace.Core.Entities.CycleLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActualCycleLength")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ActualPeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ActualPeriodStart")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AffectedTrainingPlanId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DaysDifference")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PredictedPeriodStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RunnerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("TriggeredRegeneration")
                        .HasColumnType("boolean");

                    b.Property<bool>("WasPredictionAccurate")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ActualPeriodStart");

                    b.HasIndex("AffectedTrainingPlanId");

                    b.HasIndex("ReportedAt");

                    b.HasIndex("RunnerId");

                    b.ToTable("cycle_logs", (string)null);
                });

            modelBuilder.Entity("HerPace.Core.Entities.ImportedActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActivityDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ActivityTitle")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("AverageHeartRate")
                        .HasColumnType("integer");

                    b.Property<double?>("AveragePaceSecondsPerKm")
                        .HasColumnType("double precision");

                    b.Property<int?>("Cadence")
                        .HasColumnType("integer");

                    b.Property<int?>("CaloriesBurned")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("DistanceMeters")
                        .HasColumnType("double precision");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<double?>("ElevationGainMeters")
                        .HasColumnType("double precision");

                    b.Property<string>("ExternalActivityId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("GpsRouteJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MaxHeartRate")
                        .HasColumnType("integer");

                    b.Property<int?>("MovingTimeSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("Platform")
                        .HasColumnType("integer");

                    b.Property<string>("RawResponseJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("RunnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TrainingSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrainingSessionId");

                    b.HasIndex("Platform", "ExternalActivityId")
                        .IsUnique();

                    b.HasIndex("RunnerId", "ActivityDate");

                    b.HasIndex("RunnerId", "Platform");

                    b.ToTable("imported_activities", (string)null);
                });

            modelBuilder.Entity("HerPace.Core.Entities.PlanAdaptationHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AdaptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChangesJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("SessionsAffectedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("TrainingPlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("TriggerReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("ViewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AdaptedAt")
                        .IsDescending();

                    b.HasIndex("TrainingPlanId");

                    b.ToTable("plan_adaptation_history", (string)null);
                });

            modelBuilder.Entity("HerPace.Core.Entities.Race", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CompletionStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Distance")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<int>("DistanceType")
                        .HasColumnType("integer");

                    b.Property<string>("GoalTime")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("RaceCompletionGoal")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("RaceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RaceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<TimeSpan?>("RaceResult")
                        .HasColumnType("interval");

                    b.Property<DateTime?>("ResultLoggedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RunnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("TrainingStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RaceDate");

                    b.HasIndex("RunnerId");

                    b.ToTable("races", (string)null);
                });

            modelBuilder.Entity("HerPace.Core.Entities.Runner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CycleLength")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DistanceUnit")
                        .HasColumnType("integer");

                    b.Property<int>("FitnessLevel")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("FiveKPR")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("HalfMarathonPR")
                        .HasColumnType("interval");

                    b.Property<DateTime?>("LastPeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastPeriodStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan?>("MarathonPR")
                        .HasColumnType("interval");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<TimeSpan?>("TenKPR")
                        .HasColumnType("interval");

                    b.Property<int>("TypicalCycleRegularity")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TypicalWeeklyMileage")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("runners", (string)null);
                });

            modelBuilder.Entity("HerPace.Core.Entities.SyncLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActivitiesDuplicate")
                        .HasColumnType("integer");

                    b.Property<int>("ActivitiesFiltered")
                        .HasColumnType("integer");

                    b.Property<int>("ActivitiesFound")
                        .HasColumnType("integer");

                    b.Property<int>("ActivitiesImported")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConnectedServiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("Platform")
                        .HasColumnType("integer");

                    b.Property<Guid>("RunnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<string>("SyncType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ConnectedServiceId");

                    b.HasIndex("RunnerId");

                    b.HasIndex("StartedAt")
                        .IsDescending();

                    b.ToTable("sync_logs", (string)null);
                });

            modelBuilder.Entity("HerPace.Core.Entities.TrainingPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiModel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AiRationale")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DaysAfterPeriodToReduceIntensity")
                        .HasColumnType("integer");

                    b.Property<int>("DaysBeforePeriodToReduceIntensity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GenerationSource")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastRecalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastRecalculationJobId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastRecalculationRequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastRecalculationSummary")
                        .HasColumnType("text");

                    b.Property<int>("LongRunDay")
                        .HasColumnType("integer");

                    b.Property<bool>("PendingRecalculationConfirmation")
                        .HasColumnType("boolean");

                    b.Property<string>("PendingRecalculationPreviewJson")
                        .HasColumnType("text");

                    b.Property<string>("PendingRecalculationSummary")
                        .HasColumnType("text");

                    b.Property<string>("PlanCompletionGoal")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("PreviewGeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RaceId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("RecalculationConfirmationAccepted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RecalculationConfirmationRequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RecalculationConfirmationRespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RecalculationSummaryViewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RunnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TrainingDaysPerWeek")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RaceId")
                        .IsUnique();

                    b.HasIndex("RunnerId");

                    b.HasIndex("Status");

                    b.HasIndex("RunnerId", "Status")
                        .IsUnique()
                        .HasFilter("\"Status\" = 0");

                    b.ToTable("training_plans", (string)null);
                });

            modelBuilder.Entity("HerPace.Core.Entities.TrainingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ActualDistance")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<int?>("ActualDuration")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CyclePhase")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Distance")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("HRZones")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("IntensityLevel")
                        .HasColumnType("integer");

                    b.Property<bool>("IsSkipped")
                        .HasColumnType("boolean");

                    b.Property<string>("PhaseGuidance")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("RPE")
                        .HasColumnType("integer");

                    b.Property<string>("Recovery")
                        .HasColumnType("text");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SessionDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("SessionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SkipReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("TrainingPlanId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("WarmUp")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("WorkoutTips")
                        .HasColumnType("text");

                    b.Property<int>("WorkoutType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompletedAt");

                    b.HasIndex("ScheduledDate");

                    b.HasIndex("TrainingPlanId");

                    b.ToTable("training_sessions", (string)null);
                });

            modelBuilder.Entity("HerPace.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("HerPace.Core.Entities.ConnectedService", b =>
                {
                    b.HasOne("HerPace.Core.Entities.Runner", "Runner")
                        .WithMany()
                        .HasForeignKey("RunnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Runner");
                });

            modelBuilder.Entity("HerPace.Core.Entities.CycleLog", b =>
                {
                    b.HasOne("HerPace.Core.Entities.TrainingPlan", "AffectedTrainingPlan")
                        .WithMany()
                        .HasForeignKey("AffectedTrainingPlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HerPace.Core.Entities.Runner", "Runner")
                        .WithMany()
                        .HasForeignKey("RunnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AffectedTrainingPlan");

                    b.Navigation("Runner");
                });

            modelBuilder.Entity("HerPace.Core.Entities.ImportedActivity", b =>
                {
                    b.HasOne("HerPace.Core.Entities.Runner", "Runner")
                        .WithMany()
                        .HasForeignKey("RunnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HerPace.Core.Entities.TrainingSession", "TrainingSession")
                        .WithMany()
                        .HasForeignKey("TrainingSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Runner");

                    b.Navigation("TrainingSession");
                });

            modelBuilder.Entity("HerPace.Core.Entities.PlanAdaptationHistory", b =>
                {
                    b.HasOne("HerPace.Core.Entities.TrainingPlan", "TrainingPlan")
                        .WithMany()
                        .HasForeignKey("TrainingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingPlan");
                });

            modelBuilder.Entity("HerPace.Core.Entities.Race", b =>
                {
                    b.HasOne("HerPace.Core.Entities.Runner", "Runner")
                        .WithMany("Races")
                        .HasForeignKey("RunnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Runner");
                });

            modelBuilder.Entity("HerPace.Core.Entities.Runner", b =>
                {
                    b.HasOne("HerPace.Core.Entities.User", "User")
                        .WithOne("Runner")
                        .HasForeignKey("HerPace.Core.Entities.Runner", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HerPace.Core.Entities.SyncLog", b =>
                {
                    b.HasOne("HerPace.Core.Entities.ConnectedService", "ConnectedService")
                        .WithMany("SyncLogs")
                        .HasForeignKey("ConnectedServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HerPace.Core.Entities.Runner", "Runner")
                        .WithMany()
                        .HasForeignKey("RunnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConnectedService");

                    b.Navigation("Runner");
                });

            modelBuilder.Entity("HerPace.Core.Entities.TrainingPlan", b =>
                {
                    b.HasOne("HerPace.Core.Entities.Race", "Race")
                        .WithOne("TrainingPlan")
                        .HasForeignKey("HerPace.Core.Entities.TrainingPlan", "RaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HerPace.Core.Entities.Runner", "Runner")
                        .WithMany("TrainingPlans")
                        .HasForeignKey("RunnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Race");

                    b.Navigation("Runner");
                });

            modelBuilder.Entity("HerPace.Core.Entities.TrainingSession", b =>
                {
                    b.HasOne("HerPace.Core.Entities.TrainingPlan", "TrainingPlan")
                        .WithMany("Sessions")
                        .HasForeignKey("TrainingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingPlan");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("HerPace.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("HerPace.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HerPace.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("HerPace.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HerPace.Core.Entities.ConnectedService", b =>
                {
                    b.Navigation("SyncLogs");
                });

            modelBuilder.Entity("HerPace.Core.Entities.Race", b =>
                {
                    b.Navigation("TrainingPlan");
                });

            modelBuilder.Entity("HerPace.Core.Entities.Runner", b =>
                {
                    b.Navigation("Races");

                    b.Navigation("TrainingPlans");
                });

            modelBuilder.Entity("HerPace.Core.Entities.TrainingPlan", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("HerPace.Core.Entities.User", b =>
                {
                    b.Navigation("Runner");
                });
#pragma warning restore 612, 618
        }
    }
}
