namespace HerPace.Core.Enums;

/// <summary>
/// Source of training plan generation.
/// </summary>
public enum GenerationSource
{
    AI,         // Generated by Gemini AI
    Fallback    // Generated by template fallback
}
